# Generated by Django 3.0.5 on 2020-04-04 07:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200404_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
