# Generated by Django 3.0.5 on 2020-04-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200404_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
