# Generated by Django 3.0.5 on 2020-04-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_code_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='author',
            field=models.CharField(default='Xuan Hung', max_length=50),
        ),
    ]
