# Generated by Django 3.0.5 on 2020-04-04 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_code_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cplusplus',
            fields=[
                ('code_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.CODE')),
            ],
            bases=('blog.code',),
        ),
        migrations.CreateModel(
            name='Python',
            fields=[
                ('code_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.CODE')),
            ],
            bases=('blog.code',),
        ),
    ]
